import express from "express";
import cors from "cors";
import { corsOptions } from "./config/corsConfig.js";
import authRoutes from "./src/auth/auth.route.js";
const app = express();
app.use(cors(corsOptions));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use("/api/auth", authRoutes);
export default app;